# Generated by Django 3.1.3 on 2020-11-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='nickname')),
                ('petname', models.CharField(max_length=20, null=True, verbose_name='petname')),
                ('petkind', models.CharField(choices=[('DOG', '개'), ('CAT', '고양이'), ('RAB', '토끼'), ('BIRD', '새'), ('FISH', '물고기'), ('HAM', '햄스터'), ('ETC', '기타')], default='DOG', max_length=4)),
                ('avatar', models.ImageField(blank=True, default='avatars/2.PNG', null=True, upload_to='avatars/', verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
