# Generated by Django 3.1.3 on 2020-11-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='nickname'),
        ),
    ]
