# Generated by Django 3.1.3 on 2020-11-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201201_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='petkind',
        ),
        migrations.RemoveField(
            model_name='user',
            name='petname',
        ),
    ]
