# Generated by Django 3.1.3 on 2020-11-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201201_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='nickname'),
        ),
        migrations.AddField(
            model_name='user',
            name='petkind',
            field=models.CharField(choices=[('DOG', '개'), ('CAT', '고양이'), ('RAB', '토끼'), ('BIRD', '새'), ('FISH', '물고기'), ('HAM', '햄스터'), ('ETC', '기타')], default='DOG', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='petname',
            field=models.CharField(max_length=20, null=True, verbose_name='petname'),
        ),
    ]
