# Generated by Django 3.1.3 on 2020-12-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201202_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.PNG', null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
