# Generated by Django 3.0.8 on 2020-10-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='like',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='save',
        ),
    ]
