# Generated by Django 3.0.8 on 2020-12-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_remove_recipe_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_img',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipe_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='recipe_step',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipe_step/%Y/%m/%d'),
        ),
    ]
