# Generated by Django 3.0.8 on 2020-12-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20201225_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_step',
            name='procedure',
            field=models.TextField(default='', max_length=50),
        ),
    ]
