# Generated by Django 3.0.8 on 2021-01-01 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0006_auto_20201230_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_recipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
