# Generated by Django 3.0.8 on 2021-01-01 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipe_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='save',
            new_name='save_count',
        ),
    ]
