# Generated by Django 3.0.8 on 2021-01-03 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0010_auto_20210103_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_Recipe_Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.TextField(default='', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='temp_recipe_step/%Y/%m/%d')),
                ('content', models.TextField(default='', max_length=180)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_recipe_step', to='recipe.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Recipe_Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50, null=True)),
                ('amount', models.CharField(max_length=50, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_recipe_ingredient', to='recipe.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Recipe_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='temp_recipe_img/%Y/%m/%d')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_recipe_img', to='recipe.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(default='', max_length=50)),
                ('cooking_time', models.CharField(default='', max_length=50)),
                ('title', models.TextField(default='', max_length=20)),
                ('summary', models.TextField(default='', max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(default='', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_recipe_user', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='temp_like_recipe', to=settings.AUTH_USER_MODEL)),
                ('save_count', models.ManyToManyField(blank=True, related_name='temp_save_recipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
