# Generated by Django 3.0.8 on 2021-01-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_temp_recipe_temp_recipe_img_temp_recipe_ingredient_temp_recipe_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_recipe_img',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='temp_recipe_ingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='temp_recipe_step',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Temp_Recipe',
        ),
        migrations.DeleteModel(
            name='Temp_Recipe_Img',
        ),
        migrations.DeleteModel(
            name='Temp_Recipe_Ingredient',
        ),
        migrations.DeleteModel(
            name='Temp_Recipe_Step',
        ),
    ]
