# Generated by Django 3.0.8 on 2021-01-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20210103_2113'),
        ('recipe', '0012_auto_20210103_1923'),
    ]

    operations = [
    ]
