# Generated by Django 3.0.8 on 2021-01-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_merge_20210106_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='save_count',
            new_name='bookmark',
        ),
    ]
