# Generated by Django 3.0.8 on 2021-01-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20210107_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='summary',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe_step',
            name='content',
            field=models.TextField(default='', max_length=500),
        ),
    ]
