# Generated by Django 3.0.8 on 2021-01-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='remessage',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
