# Generated by Django 3.0.8 on 2020-12-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20201228_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
    ]
