# Generated by Django 3.0.8 on 2020-12-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20201228_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created']},
        ),
    ]
