# Generated by Django 3.0.8 on 2020-12-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20201230_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='question',
            name='accept_done',
            field=models.BooleanField(default=False),
        ),
    ]
