# Generated by Django 3.0.8 on 2020-12-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.TextField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.CharField(default='', max_length=50),
        ),
    ]
