# Generated by Django 3.0.8 on 2020-12-22 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20201220_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='like',
        ),
    ]
