# Generated by Django 3.0.8 on 2021-01-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_review_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
