# Generated by Django 3.0.8 on 2021-01-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20210103_1913'),
        ('review', '0007_auto_20210103_2113'),
    ]

    operations = [
    ]
