# Generated by Django 3.0.8 on 2020-12-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('content', models.TextField(default='', max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Report_problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('reason', models.CharField(default='', max_length=50)),
                ('other_reason', models.TextField(default='', max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Service_center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('content', models.TextField(default='', max_length=180)),
            ],
        ),
    ]
