# Generated by Django 3.0.8 on 2020-12-22 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_problem',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='report_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report_problem',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reported_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
