# Generated by Django 3.0.8 on 2020-12-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_auto_20201222_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_problem',
            old_name='user',
            new_name='username',
        ),
    ]
